title: Hao Ying
show_author: false 
theme: minima
markdown: kramdown
kramdown:
  math_engine: mathjax
description: >
  Ph.D. Candidate in Pure Mathematics, Zhejiang University.
 % Representation theory of real reductive groups and Dirac operators.
show_excerpts: false
