title: Hao Ying
theme: minima
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: false
description: >
  Ph.D. in Pure Mathematics.  
  Representation theory of real reductive groups, Dirac operators, and related cohomology questions.
show_excerpts: false
